name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 16
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Paperclip
        run: ./gradlew paperclip
      - name: upload Purpur-server
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Purpur-Server/build/libs/
      - name: upload Paperclip
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./purpur-paperclip.jar
